spring.application.name=BookMarket
server.servlet.context-path=/BookMarket

spring.servlet.multipart.enabled=true
spring.servlet.multipart.file-size-threshold=2KB
spring.servlet.multipart.location=D:/upload
spring.servlet.multipart.max-file-size=200MB
spring.servlet.multipart.max-request-size=215MB

file.uploadDir=D:/upload/

# Tomcat Upload Limit
server.tomcat.max-http-form-post-size=200MB
server.tomcat.max-swallow-size=200MB
server.tomcat.max-part-count=50

spring.messages.encoding=UTF-8
spring.messages.basename=messages/messages